<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260602214255 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE patient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(100) NOT NULL, lastname VARCHAR(100) NOT NULL, birth_date DATE NOT NULL, gender VARCHAR(5) DEFAULT NULL, height INT DEFAULT NULL, weight INT DEFAULT NULL, job VARCHAR(100) DEFAULT NULL, sport VARCHAR(100) DEFAULT NULL, laterality VARCHAR(6) DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1ADAD7EBA76ED395 ON patient (user_id)');
        $this->addSql('CREATE TABLE patient_physio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_primary BOOLEAN NOT NULL, assigned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, patient_id INT NOT NULL, workplace_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_315EEC2C6B899279 ON patient_physio (patient_id)');
        $this->addSql('CREATE INDEX IDX_315EEC2CAC25FB46 ON patient_physio (workplace_id)');
        $this->addSql('CREATE INDEX IDX_315EEC2CA76ED395 ON patient_physio (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, firstname VARCHAR(100) NOT NULL, lastname VARCHAR(100) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_workplace (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, user_id INT NOT NULL, workplace_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D01B1F0AA76ED395 ON user_workplace (user_id)');
        $this->addSql('CREATE INDEX IDX_D01B1F0AAC25FB46 ON user_workplace (workplace_id)');
        $this->addSql('CREATE TABLE workplace (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(255) DEFAULT NULL, town VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EBA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_physio ADD CONSTRAINT FK_315EEC2C6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_physio ADD CONSTRAINT FK_315EEC2CAC25FB46 FOREIGN KEY (workplace_id) REFERENCES workplace (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_physio ADD CONSTRAINT FK_315EEC2CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_workplace ADD CONSTRAINT FK_D01B1F0AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_workplace ADD CONSTRAINT FK_D01B1F0AAC25FB46 FOREIGN KEY (workplace_id) REFERENCES workplace (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT FK_1ADAD7EBA76ED395');
        $this->addSql('ALTER TABLE patient_physio DROP CONSTRAINT FK_315EEC2C6B899279');
        $this->addSql('ALTER TABLE patient_physio DROP CONSTRAINT FK_315EEC2CAC25FB46');
        $this->addSql('ALTER TABLE patient_physio DROP CONSTRAINT FK_315EEC2CA76ED395');
        $this->addSql('ALTER TABLE user_workplace DROP CONSTRAINT FK_D01B1F0AA76ED395');
        $this->addSql('ALTER TABLE user_workplace DROP CONSTRAINT FK_D01B1F0AAC25FB46');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE patient_physio');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_workplace');
        $this->addSql('DROP TABLE workplace');
    }
}
