<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260603160942 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, video_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE pathology (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, estimated_recovery_days INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE patient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(100) NOT NULL, lastname VARCHAR(100) NOT NULL, birth_date DATE NOT NULL, gender VARCHAR(5) DEFAULT NULL, height INT DEFAULT NULL, weight INT DEFAULT NULL, job VARCHAR(100) DEFAULT NULL, sport VARCHAR(100) DEFAULT NULL, laterality VARCHAR(6) DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1ADAD7EBA76ED395 ON patient (user_id)');
        $this->addSql('CREATE TABLE patient_case (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, started_at DATE NOT NULL, ended_at DATE DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F199D4CC6B899279 ON patient_case (patient_id)');
        $this->addSql('CREATE TABLE patient_case_pathology (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_case_id INT NOT NULL, pathology_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4825DF239273811E ON patient_case_pathology (patient_case_id)');
        $this->addSql('CREATE INDEX IDX_4825DF23CE86795D ON patient_case_pathology (pathology_id)');
        $this->addSql('CREATE TABLE patient_case_physio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_primary BOOLEAN NOT NULL, started_at DATE NOT NULL, ended_at DATE DEFAULT NULL, patient_case_id INT NOT NULL, workplace_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A3FD7D309273811E ON patient_case_physio (patient_case_id)');
        $this->addSql('CREATE INDEX IDX_A3FD7D30AC25FB46 ON patient_case_physio (workplace_id)');
        $this->addSql('CREATE INDEX IDX_A3FD7D30A76ED395 ON patient_case_physio (user_id)');
        $this->addSql('CREATE TABLE session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_date DATE NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_case_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D044D5D49273811E ON session (patient_case_id)');
        $this->addSql('CREATE INDEX IDX_D044D5D4B03A8386 ON session (created_by_id)');
        $this->addSql('CREATE TABLE session_exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sets INT DEFAULT NULL, repetitions INT DEFAULT NULL, duration VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, session_id INT NOT NULL, exercise_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2576B574613FECDF ON session_exercise (session_id)');
        $this->addSql('CREATE INDEX IDX_2576B574E934951A ON session_exercise (exercise_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, firstname VARCHAR(100) NOT NULL, lastname VARCHAR(100) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_workplace (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, user_id INT NOT NULL, workplace_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D01B1F0AA76ED395 ON user_workplace (user_id)');
        $this->addSql('CREATE INDEX IDX_D01B1F0AAC25FB46 ON user_workplace (workplace_id)');
        $this->addSql('CREATE TABLE workplace (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(255) DEFAULT NULL, town VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EBA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_case ADD CONSTRAINT FK_F199D4CC6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_case_pathology ADD CONSTRAINT FK_4825DF239273811E FOREIGN KEY (patient_case_id) REFERENCES patient_case (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_case_pathology ADD CONSTRAINT FK_4825DF23CE86795D FOREIGN KEY (pathology_id) REFERENCES pathology (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_case_physio ADD CONSTRAINT FK_A3FD7D309273811E FOREIGN KEY (patient_case_id) REFERENCES patient_case (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_case_physio ADD CONSTRAINT FK_A3FD7D30AC25FB46 FOREIGN KEY (workplace_id) REFERENCES workplace (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_case_physio ADD CONSTRAINT FK_A3FD7D30A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D49273811E FOREIGN KEY (patient_case_id) REFERENCES patient_case (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D4B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_exercise ADD CONSTRAINT FK_2576B574613FECDF FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_exercise ADD CONSTRAINT FK_2576B574E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_workplace ADD CONSTRAINT FK_D01B1F0AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_workplace ADD CONSTRAINT FK_D01B1F0AAC25FB46 FOREIGN KEY (workplace_id) REFERENCES workplace (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE patient DROP CONSTRAINT FK_1ADAD7EBA76ED395');
        $this->addSql('ALTER TABLE patient_case DROP CONSTRAINT FK_F199D4CC6B899279');
        $this->addSql('ALTER TABLE patient_case_pathology DROP CONSTRAINT FK_4825DF239273811E');
        $this->addSql('ALTER TABLE patient_case_pathology DROP CONSTRAINT FK_4825DF23CE86795D');
        $this->addSql('ALTER TABLE patient_case_physio DROP CONSTRAINT FK_A3FD7D309273811E');
        $this->addSql('ALTER TABLE patient_case_physio DROP CONSTRAINT FK_A3FD7D30AC25FB46');
        $this->addSql('ALTER TABLE patient_case_physio DROP CONSTRAINT FK_A3FD7D30A76ED395');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT FK_D044D5D49273811E');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT FK_D044D5D4B03A8386');
        $this->addSql('ALTER TABLE session_exercise DROP CONSTRAINT FK_2576B574613FECDF');
        $this->addSql('ALTER TABLE session_exercise DROP CONSTRAINT FK_2576B574E934951A');
        $this->addSql('ALTER TABLE user_workplace DROP CONSTRAINT FK_D01B1F0AA76ED395');
        $this->addSql('ALTER TABLE user_workplace DROP CONSTRAINT FK_D01B1F0AAC25FB46');
        $this->addSql('DROP TABLE exercise');
        $this->addSql('DROP TABLE pathology');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE patient_case');
        $this->addSql('DROP TABLE patient_case_pathology');
        $this->addSql('DROP TABLE patient_case_physio');
        $this->addSql('DROP TABLE session');
        $this->addSql('DROP TABLE session_exercise');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_workplace');
        $this->addSql('DROP TABLE workplace');
    }
}
